excluded:
  - Pods
  - RT-ITV
  - Tv(Common)/Vendors
  - Tv(iOS)/Vendors
  - Tv(tvOS)/Vendors
disabled_rules:
  - todo
  - trailing_whitespace
  - force_cast
  - redundant_optional_initialization
  - notification_center_detachment
  #todo посмотреть правило:
  - nesting
opt_in_rules:
  - explicit_init
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
identifier_name:
  min_length: 1
large_tuple:
  warning: 4
  error: 5
line_length:
  warning: 160
  error: 250
function_body_length:
  warning: 70
  error: 100
type_body_length:
  warning: 250
  error: 300
file_length:
  warning: 600
  error: 1000
